import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import NavbarWrapper from "../../components/NavbarWrapper";
import CustomCursor from "../../components/CustomCursor";
import Footer from "../../components/Footer";

// 1. Orbitron Font Setup (Robotic Look ke liye)
const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Robo Rumble",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`
            ${geistSans.variable} 
            ${geistMono.variable} 
            ${orbitron.variable} 
            antialiased 
            
            /* --- SCROLL & LAYOUT FIXES --- */
            overflow-x-hidden  /* Horizontal scroll (hilna) band */
            w-full             /* Full width ensure karega */
            relative           /* Navbar positioning ke liye stable base */
            bg-[#020617]       /* Dark background default */
            text-white         /* White text default */
            flex flex-col
            min-h-screen
          `}
        >
          <CustomCursor />
          <NavbarWrapper />
          <div className="flex-grow">
            {children}
          </div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
